### ISSUE TITLE
自动清理功能，move不起作用

### ISSUE THREAD

**Issue by huleiya** [SmallPeaches/DanmakuRender#126]
上传视频后直接清理了，并没有将上传的视频复制或移动到指定文件夹，这里的method设置成move或copy都不行，配置文件的自动清理部分如下：
```
# 自动清理
clean:
  # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
  # 请注意：清理过程不可逆！最好还是自己手动清理！
  src_video:
    - method: copy
      dest: './直播回放/{STREAMER}{YEAR}年{MONTH}月{DAY}日'
      delay: 0
    - method: delete
      delay: 0

  dm_video:
    - method: delete
      delay: 172800
```
