### ISSUE TITLE
自动清理功能问题

### ISSUE THREAD

**Issue by ixjx** [SmallPeaches/DanmakuRender#153]
```yaml
# 自动清理
clean:
  # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
  # 请注意：清理过程不可逆！最好还是自己手动清理！
  method: delete

  # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
  dest: ~

  # 只处理上传完成的视频，此功能暂时只在启用实时上传时有效，默认true
  # 如果想在只上传弹幕视频时自动清理原视频，请设置为false
  # 特别提示：既上传原视频又设置为false可能会导致不可控的结果！
  strict: True

  # 清理延迟（秒），在上传完成后会过一段时间再清理，默认172800（48小时）
  delay: 172800
```

按照如上配置文件
只上传弹幕视频，自动清理只会清理掉弹幕视频，原视频和弹幕文件会被保留
如何才能做到清理所有文件呢
