### ISSUE TITLE
5900x+3070ti单线程3倍速

### ISSUE THREAD

**Issue by RAINighty** [SmallPeaches/DanmakuRender#154]
rt，双线程有7倍速左右，单线程video encorder仅50%左右，双线程才能跑满100%

replay.yml配置表
```
# 渲染参数
render:
  # 同时执行的渲染任务数，默认1，若渲染时CPU和GPU使用都低于80%可以调高这个，一般情况下设置应该小于5
  # 特别提示：如果渲染一个CPU或者显卡占用都很高，调高这个反而有副作用！
  nrenders: 2
  
  # 渲染输出文件夹，默认为空（在录制输出文件夹后面加上“带弹幕版”）
  output_dir: ~

  # 生成的视频文件格式，默认mp4
  format: mp4
  
  # 硬件解码参数，默认由FFmpeg自动判断，如果出现问题可以设为空
  hwaccel_args: [-hwaccel, auto]

  # 视频编码器，NVIDIA设置为h264_nvenc，AMD设置为h264_amf，CPU设置为libx264
  vencoder: h264_nvenc

  # 视频编码器参数，默认恒定码率15Mbps
  vencoder_args: [-b:v, 15M]

  # 音频编码器
  aencoder: aac

  # 音频编码器参数，默认恒定码率320Kbps
  aencoder_args: [-b:a, 320K]

  # 输出重缩放，会把输出重缩放到指定分辨率，可以设置为'WxH'直接指定输出分辨率，例如'3840x2160'（4K）
  # 也可以指定为当前视频的大小倍数，例如'1.5'，这样1080P视频将会被放大到2880x1620（这个也符合了B站的4K视频标准）
  output_resize: 1

  # 高级渲染参数，具体可用选项请参考文档
  advanced_render_args: ~

# 上传参数
uploader:
  nuploaders: 1

replay:
  test:
    url: 'https://live.bilibili.com/2455978'
    segment: 3600

```

由于我只进行渲染所以可能没有日志（或者是我没找到）
