### ISSUE TITLE
你好开发者，关于自动清理配置我想请教下

### ISSUE THREAD

**Issue by ikun1993** [SmallPeaches/DanmakuRender#194]
前提我设置了原视频和弹幕版均设置上传

因为原视频是主播下播后上传  弹幕版为压制好上传

但是我现在遇到了，配置自动清理出错了 ，下面设置好像达不到我想要的投稿上传复制另一个文件夹 然后弹幕压制好删除文件，请问要如何修改，我现在通过脚本实现。

```
# 自动清理
clean:
  dm_video: 
      method: copy
      dest: /opt/onedrive/主播-id
  src_video:
      method: delete
      delay: 600 # 10分钟
      w_srcfile: True
```
