### ISSUE TITLE
想請問一下移動檔案 怎麼修改參數 謝謝

### ISSUE THREAD

**Issue by Bao0224** [SmallPeaches/DanmakuRender#294]
不好意思 是一個新手
想詢問一下要如何移動檔案呢
我的需求是
錄製斗魚 然後有渲染彈幕的影片
我沒有要自動上傳B站 我手動的
# 上传参数，如果不需要上传就把下面的都删了

所以上傳參數這我照說明都刪除了

=====

我想詢問要如何把錄製好的影片 跟渲染好的彈幕影片 在它們完成好一個影片檔後
可以自動轉移到我D槽 我指定的資料夾呢 謝謝

我目前因為硬碟健康度的關係 
暫時是用Y槽 用RAMDISK的方式隔一個XYZ資料夾 來錄製影片跟渲染好的彈幕影片
但是如果臨時跳電重開機 我沒及時手動轉移完成的影片到D槽的ABC資料夾 這樣就會消失了

我看下面的參數似乎可以自動移動檔案 如果行 可以教教我 這些參數該怎麼寫嗎 謝謝
這樣我就不用定鬧鐘 每隔一小時多移動一次渲染好的彈幕影片
謝謝你

# 自动清理
clean:
  # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
  # 请注意：清理过程不可逆！最好还是自己手动清理！
  method: ~

  # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
  dest: ~

**Comment by haha252** [comment]
emmm，你好，下次在粘貼配製文件的時候可以使用Markdown語法，就是github文本框右上角的那些工具，這樣可以讓配置文件有好的觀感。例如
源文檔
```
### 標題
你好啊，這是我的配置文件
`config`
```
可以變為
### 標題
你好啊，這是我的配置文件
`config`

這樣我們看的時候也會清楚的知道你的配置文件是什麼樣子哦~謝謝理解啦

**Comment by haha252** [comment]
根據您的需求，我大概編寫了以下的配置文件：
```
clean_args:

  all:
    # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
    # 注意：清理过程不可逆！
    method: move
    # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
    dest: D:/直播錄製/{STREAMER.NAME}/
    # 清理延迟（秒），默认86400（24小时）
    delay: 0
    # 清理弹幕视频时同时清理原文件，默认false
    # 请注意，此功能应该只在不上传原文件的情况下使用，否则会导致上传失败
    w_srcfile: False
    # 清理源文件时同时清理转码前文件（如果有的话），默认true
    w_srcpre: True
```
這一個配置文件會在直播結束後，自動將錄製好的文件複製到`D:/直播錄製/{STREAMER.NAME}/`文件夾，{STREAMER.NAME}是變量。例如我錄製的主播叫`哈哈`，那麼就會自動複製到`D:/直播錄製/哈哈/`去
