### ISSUE TITLE
[疑问]能在不重启程序的情况下更新配置吗？

### ISSUE THREAD

**Issue by RAINighty** [SmallPeaches/DanmakuRender#315]
我看global.yml里的
```
# DMR引擎参数
dmr_engine_args: 
  # 选择组件
  enabled_plugins: ['downloader', 'render', 'uploader', 'cleaner']
  # 是否动态更新配置文件
  dynamic_config: True
  # 动态更新的配置文件路径
  dynamic_config_path: ./configs
```
这个似乎不能自动读取修改后的配置文件？
