### ISSUE TITLE
[支持请求]关于自定义上传的使用方法的相关问题

### ISSUE THREAD

**Issue by haha252** [SmallPeaches/DanmakuRender#403]
今天看自动上传功能感觉非常有用，遂自己写了一个上传脚本上传文件，并验证可以使用，但是并没有在文档中找到配置文件的写法（可能是我瞎了？有的话求指路）qwq

目前唯一的线索在`global.yml`，内容如下
```yml
  # 完全自定义上传
  # 调用的上传程序应该在上传成功后返回0，失败返回非0，并将错误信息输出到stderr
  # 具体说明请参考GitHub文档
  custom:
    # 上传引擎，目前只支持子进程调用
    engine: subprocess
    # 重试次数，如果上传遇到错误将会重试，设置为0表示不重试
    # 注意：重试会整个视频重传，并且阻塞后面视频的上传，不应该设置太大
    retry: 3
    # 上传超时时间（秒），如果上传时间超过这个时间将会被强制终止（用于防止卡死），0表示不限制
    timeout: 0
    # 上传的视频最短长度，小于此长度的视频会被自动过滤，默认120s
    min_length: 120
    # 上传命令行参数，可以使用关键字替换
    # 为保证安全调用，请使用参数列表的形式，例如：['python', 'upload.py', '{PATH}']
    command: ~
```

我试了在每个项目的配置文件中写了如下配置，但是都不工作qwq：

```yml
# 上传参数，如果不需要上传就把下面的都删了
upload_args:
  # 完全自定义上传
  # 调用的上传程序应该在上传成功后返回0，失败返回非0，并将错误信息输出到stderr
  # 具体说明请参考GitHub文档
  custom:
    # 上传引擎，目前只支持子进程调用
    engine: subprocess
    # 重试次数，如果上传遇到错误将会重试，设置为0表示不重试
    # 注意：重试会整个视频重传，并且阻塞后面视频的上传，不应该设置太大
    retry: 3
    # 上传超时时间（秒），如果上传时间超过这个时间将会被强制终止（用于防止卡死），0表示不限制
    timeout: 0
    # 上传的视频最短长度，小于此长度的视频会被自动过滤，默认120s
    min_length: 120
    # 上传命令行参数，可以使用关键字替换
    # 为保证安全调用，请使用参数列表的形式，例如：['python', 'upload.py', '{PATH}']
    command: （此处省略）
```

```yml
upload_args:
  ‘*.flv'
    custom:
      engine: subprocess
      retry: 3
      timeout: 0
      min_length: 120
      command: （此处省略）
```

```yml
upload_args:
  src_video:
    custom:
      engine: subprocess
      retry: 3
      timeout: 0
      min_length: 120
      command: （此处省略）
```

后台有正常录制完成的输出但是没有上传的输出。求指点！

**Comment by SmallPeaches** [comment]
上传到非B站需要显式指定上传目标，例如：
```yaml
src_video:
  target: custom
  engine: subprocess
  realtime: true    # 必须用实时上传
  command: ...
  ...
```

**Comment by haha252** [comment]
能用了！感谢老师！对了我能再问一下自动清理里面的custom怎么用吗

**Comment by haha252** [comment]
还有就是说，如果我既想要上传到b站，又想要自定义上传，这个怎么操作呢？如果我这样写：

```yml
    src_video: 
    account: （此处省略）
    cookies: （此处省略）
    . . .

   src_video:
     target: custom
     engine: subprocess
     realtime: true    # 必须用实时上传
     command: （此处省略）
```
这样就貌似不符合yml文件的语法了。因为`Map keys must be unique`

我研究了一下代码，然后询问了deepseek，得到的答复是先去编辑global.yml：
```yml
upload_args:
  # B站标准配置
  bilibili:
    engine: biliuprs
    account: "default_bili"
    retry: 3
    expire: 86400
  
  # 自定义上传配置模板
  custom_template: &custom_base
    engine: subprocess
    realtime: true
    timeout: 300
    stateless: true
```
再编辑DMR配置文件：
```yml
upload_args:
  # 原始视频文件类型
  src_video: 
    - target: bilibili  # 第一个目标：B站
      title: "直播原始录像 {date}"
      source: "原始源"
    
    - target: custom    # 第二个目标：自定义
      <<: *custom_base  # 继承全局模板
      command:
        - "/usr/bin/rsync"
        - "-avzP"
        "{path}"
        "backup@server:/live_backup/{streamer}/"
  
  # 转码后文件类型 
  rendered:
    - target: bilibili  # B站转码版
      quality: 1080p
      watermark: true
    
    - target: custom    # 云存储
      <<: *custom_base
      command:
        - "python3"
        - "/opt/scripts/s3_upload.py"
        "--file={path}"
        "--bucket=live-vod"
```
但是貌似并不可行（或许是我哪里搞错、理解错了？）
请老师指路！谢谢！

**Comment by haha252** [comment]
亦或者是这样？我试试！
```yml
  src_video: 
    - target: bilibili
      account: （略）
      cookies: （略）
      tid: 65
      cover: '（略）'
      desc: （略）
      tag: '（略）'

    - target: custom
      engine: subprocess
      realtime: true    # 必须用实时上传
      command: （略）
```
