### ISSUE TITLE
用dryrun测试 可以下载上传，用main 能下载但是上传失败

### ISSUE THREAD

**Issue by nojump** [SmallPeaches/DanmakuRender#434]

**Comment by SmallPeaches** [comment]
具体错误是什么？

**Comment by haha252** [comment]
有句名言，没有日志就是闭眼开车
发日志吧

**Comment by nojump** [comment]
> 具体错误是什么？

![Image](https://github.com/user-attachments/assets/f2c79179-3f71-4011-851f-a435704df3a5)

**Comment by nojump** [comment]
> 有句名言，没有日志就是闭眼开车 发日志吧

![Image](https://github.com/user-attachments/assets/6682868d-f565-41ce-ac1f-c2f958f4d68b)

**Comment by SmallPeaches** [comment]
你打开logs文件夹里面的日志文件看下具体报错？

**Comment by haha252** [comment]
应该是上传的配置文件有问题，可以把配置文件发一下*记得脱敏

**Comment by nojump** [comment]
> 你打开logs文件夹里面的日志文件看下具体报错？

[DMR-20250605.log](https://github.com/user-attachments/files/20608479/DMR-20250605.log)

**Comment by nojump** [comment]
> 应该是上传的配置文件有问题，可以把配置文件发一下*记得脱敏

[DMR-20250605.log](https://github.com/user-attachments/files/20608489/DMR-20250605.log)

**Comment by haha252** [comment]
应该是上传线路的问题，可以换一个线路。
日志406行中有提到，在您的直播录制配置文件中，有指定biliup的上传线路`  "line": "bldsa",`，应该就是这个的问题。
解决方案：
1.留空，交由biliuprs自行选择
2.改为其他配置文件中指定的项，具体可以参考[Biliup-rs上传线路表](https://biliup.github.io/upload-systems-analysis.html)

**Comment by haha252** [comment]
> > 应该是上传的配置文件有问题，可以把配置文件发一下*记得脱敏
> 
> [DMR-20250605.log](https://github.com/user-attachments/files/20608489/DMR-20250605.log)

应该是上传线路的问题，可以换一个线路。
日志406行中有提到，在您的直播录制配置文件中，有指定biliup的上传线路`  "line": "bldsa",`，应该就是这个的问题。
解决方案：
1.留空，交由biliuprs自行选择
2.改为其他配置文件中指定的项，具体可以参考[Biliup-rs上传线路表](https://biliup.github.io/upload-systems-analysis.html)

**Comment by nojump** [comment]
> > > 应该是上传的配置文件有问题，可以把配置文件发一下*记得脱敏
> > 
> > 
> > [DMR-20250605.log](https://github.com/user-attachments/files/20608489/DMR-20250605.log)
> 
> 应该是上传线路的问题，可以换一个线路。 日志406行中有提到，在您的直播录制配置文件中，有指定biliup的上传线路` "line": "bldsa",`，应该就是这个的问题。 解决方案： 1.留空，交由biliuprs自行选择 2.改为其他配置文件中指定的项，具体可以参考[Biliup-rs上传线路表](https://biliup.github.io/upload-systems-analysis.html)

非常感谢，我去换个线路试试看。

**Comment by nojump** [comment]
> > > 应该是上传的配置文件有问题，可以把配置文件发一下*记得脱敏
> > 
> > 
> > [DMR-20250605.log](https://github.com/user-attachments/files/20608489/DMR-20250605.log)
> 
> 应该是上传线路的问题，可以换一个线路。 日志406行中有提到，在您的直播录制配置文件中，有指定biliup的上传线路` "line": "bldsa",`，应该就是这个的问题。 解决方案： 1.留空，交由biliuprs自行选择 2.改为其他配置文件中指定的项，具体可以参考[Biliup-rs上传线路表](https://biliup.github.io/upload-systems-analysis.html)

所有线路我都试了，全部无法上传

[DMR-20250605.log](https://github.com/user-attachments/files/20609981/DMR-20250605.log)

**Comment by haha252** [comment]
> 所有线路我都试了，全部无法上传
> 
> [DMR-20250605.log](https://github.com/user-attachments/files/20609981/DMR-20250605.log)

你试试下面这个配置文件呢？
你的`global.yml`应该是没动过的（动过的话用默认配置覆盖），把你原来那个配置文件用下面这个配置文件覆盖。
这个配置文件用了最小原则，应该可以用了
```
# 本文件一个代表一个录制任务，这里的设置基本上包含了所有可用的参数
# 配置文件编写请参考 https://github.com/SmallPeaches/DanmakuRender 
common_event_args:
  # 启动自动渲染
  auto_render: True
  # 启动自动上传
  auto_upload: True
  # 启动自动清理
  auto_clean: True
  # 原视频自动转码
  auto_transcode: False

# 下载参数
download_args:
  # 下载类型
  dltype: live
  # 直播间链接
  url: 'https://www.huya.com/bbwen'
  # 录制输出文件夹，设置为空则使用任务名称作为文件夹
  output_dir: ./recording/bbwen

# 上传参数，如果不需要上传就把下面的都删了
upload_args:
  # 原视频
  src_video: 
    # 上传账号名称，程序依靠这个来识别不同的账号，如果打算传不同账号就要设置不同的名称
    account: bilibili
    # 上传cookies路径，如果设置为空将会保存到./login_info/{ACCOUNT}.json
    cookies: ~
    # 重试次数，如果上传遇到错误将会重试，设置为0表示不重试
    # 注意：重试会整个视频重传，并且阻塞后面视频的上传，不应该设置太大
    retry: 3
    # 实时上传（边录边传），每录制一个分段上传一次，同一场直播的不同分P仍然会在一个视频下，默认开启
    # 注意：实时上传可能无法上传很短的视频，尤其是在网速较快的情况下（B站对修改稿件的间隔有限制）
    realtime: True
    # 上传的视频最短长度，小于此长度的视频会被自动过滤，默认120s
    min_length: 120
    # 以下参数来自biliuprs，详细内容可以参考 https://biliup.github.io/biliup-rs/index.html
    # 是否为转载视频 1-自制 2-转载
    copyright: 1
    # 转载来源，转载视频必填
    source: ''
    # 分区号，分区参考 https://biliup.github.io/tid-ref.html
    tid: 65
    # 封面，指向本地文件地址
    cover: ''
    # 标题，可以使用关键字替换
    # 默认的例子：[飞天狙想要努力变胖/直播回放] 晚上七点半比赛 2023年2月24日 （带弹幕版）
    title: '[{STREAMER.NAME}/直播回放] {TITLE} {CTIME.YEAR}年{CTIME.MONTH:02d}月{CTIME.DAY:02d}日'
    # 简介，可以使用关键字替换
    desc: |
      {STREAMER.NAME} 的直播回放
      标题：{TITLE} 
      时间：{CTIME.YEAR}年{CTIME.MONTH:02d}月{CTIME.DAY:02d}日
      直播地址：{STREAMER.URL} 

      ————————————
      由DanmakuRender录制：
      https://github.com/SmallPeaches/DanmakuRender
    # 标签（一定要有！多个标签逗号分割）
    tag: '直播回放'

clean_args:
  all:
    # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
    # 注意：清理过程不可逆！
    method: delete
    # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
    dest: ~
    # 清理延迟（秒），默认86400（24小时）
    delay: 86400
    # 清理弹幕视频时同时清理原文件，默认false
    # 请注意，此功能应该只在不上传原文件的情况下使用，否则会导致上传失败
    w_srcfile: False
    # 清理源文件时同时清理转码前文件（如果有的话），默认true
    w_srcpre: True

```
