### ISSUE TITLE
怎么给不同的直播间设置不同的渲染参数呢？

### ISSUE THREAD

**Issue by 108muu** [SmallPeaches/DanmakuRender#83]
比如第一个直播间渲染时15M码率，第二个直播间10M码率

**Comment by redkins** [comment]
录制多个直播间，通过修改replay.yml可以指定相关参数,参数具体可参考default.yml
```yaml
# replay.yml
render: 
  hwaccel_args: [-hwaccel,cuda,-noautorotate] # 硬件解码参数，不同平台设置不一样，一般情况下不是N卡都设置为空比较好
  vencoder: hevc_nvenc                        # 使用NVIDIA NVENC H.265编码器
  vencoder_args: ['b:v','15M']                # 特殊指定编码器参数，可用参数根据编码器不同而不同

replay:
  - url: https://live.bilibili.com/13308358
```
